name: tests API

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm install
            - run: npm test
            - name: Upload test results
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: test-results
                  path: |
                      coverage
                      *.log
